"use client";
import { useEffect, useState } from "react";
import "./App.css";
import "./Tickets.css";

const tickets = [
  ["#SQ-1048","Ayesha Khan","Unable to update billing method","High","Open","4 min"],
  ["#SQ-1047","Hamza Ali","Need help with team invitation","Medium","Pending","18 min"],
  ["#SQ-1046","Sara Ahmed","Export report is ready","Low","Resolved","42 min"],
  ["#SQ-1045","Usman Raza","API access configuration","High","Open","1 hr"],
];
const nav = ["Overview","AI Assistant","Tickets","Customers","Knowledge","Analytics"];
const API_URL=(import.meta.env.VITE_API_URL||"http://127.0.0.1:8000").replace(/\/$/,"");

export default function Home(){
 const [token,setToken]=useState(()=>localStorage.getItem("supportiq_token")||"");
 const [email,setEmail]=useState("usaid@example.com");
 const [password,setPassword]=useState("Test@12345");
 const [loginError,setLoginError]=useState("");
 const [loading,setLoading]=useState(false);
 const [active,setActive]=useState("Overview");
 const [message,setMessage]=useState("");
 const [chat,setChat]=useState([{bot:true,text:"Hi! I’m SupportIQ. Ask about billing, integrations, your account, or create a ticket."}]);
 const [liveTickets,setLiveTickets]=useState<Array<{id:number;subject:string;description:string;priority:string;status:string;created_at:string}>>([]);
 const [ticketForm,setTicketForm]=useState({subject:"",description:"",priority:"medium"});
 const [ticketMessage,setTicketMessage]=useState("");
 const login=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setLoginError("");try{const body=new URLSearchParams();body.set("username",email);body.set("password",password);const res=await fetch(`${API_URL}/api/auth/login`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});if(!res.ok)throw new Error("Email or password is incorrect");const data=await res.json();localStorage.setItem("supportiq_token",data.access_token);setToken(data.access_token)}catch(err){setLoginError(err instanceof Error?err.message:"Login failed")}finally{setLoading(false)}};
 const logout=()=>{localStorage.removeItem("supportiq_token");setToken("")};
 const send=async()=>{const value=message.trim();if(!value||loading)return;setChat(x=>[...x,{bot:false,text:value}]);setMessage("");setLoading(true);try{const res=await fetch(`${API_URL}/api/chat`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({message:value})});if(res.status===401){logout();throw new Error("Session expired. Please sign in again.")}if(!res.ok)throw new Error("AI service is unavailable");const data=await res.json();setChat(x=>[...x,{bot:true,text:data.response}])}catch(err){setChat(x=>[...x,{bot:true,text:err instanceof Error?err.message:"Something went wrong"}])}finally{setLoading(false)}};
 const loadTickets=async()=>{if(!token)return;try{const res=await fetch(`${API_URL}/api/tickets`,{headers:{Authorization:`Bearer ${token}`}});if(res.ok)setLiveTickets(await res.json())}catch{setTicketMessage("Backend connection unavailable")}};
 const createTicket=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setTicketMessage("");try{const res=await fetch(`${API_URL}/api/tickets`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify(ticketForm)});if(!res.ok)throw new Error("Ticket could not be created");setTicketForm({subject:"",description:"",priority:"medium"});setTicketMessage("Ticket created successfully");await loadTickets()}catch(err){setTicketMessage(err instanceof Error?err.message:"Something went wrong")}finally{setLoading(false)}};
 useEffect(()=>{if(active==="Tickets")loadTickets()},[active,token]);
 if(!token)return <main className="loginPage"><section className="loginCard"><div className="loginBrand"><i>S</i><div><b>SupportIQ</b><span>AI customer success platform</span></div></div><div className="loginCopy"><span>SECURE WORKSPACE</span><h1>Welcome back</h1><p>Sign in to manage customer conversations, AI resolutions and support tickets.</p></div><form onSubmit={login}><label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{loginError&&<p className="loginError">{loginError}</p>}<button disabled={loading}>{loading?"Signing in...":"Sign in to SupportIQ →"}</button></form><small>Demo: usaid@example.com / Test@12345</small></section><aside><span>AI-POWERED SUPPORT</span><h2>Turn every customer conversation into a better experience.</h2><div><article><b>82%</b><small>AI resolution rate</small></article><article><b>94.8%</b><small>Customer satisfaction</small></article></div></aside></main>;
 return <main className="shell">
  <aside className="sidebar"><div className="brand"><i>S</i><div><b>SupportIQ</b><small>AI customer success</small></div></div><nav>{nav.map((n,i)=><button key={n} className={active===n?"active":""} onClick={()=>setActive(n)}><span>{["⌁","✦","▱","♙","◫","⌁"][i]}</span>{n}</button>)}</nav><div className="sideBottom"><div className="upgrade"><b>Unlock Pro insights</b><span>Advanced reports and AI automations.</span><button>View plan</button></div><div className="profile"><i>UQ</i><div><b>Usaid Qadeer</b><span>Administrator</span></div></div></div></aside>
  <section className="workspace"><header><div><small>Workspace / {active}</small><h1>{active}</h1></div><div className="actions"><button>⌕</button><button onClick={logout} title="Sign out">↪</button><button className="ask" onClick={()=>setActive("AI Assistant")}>✦ Ask SupportIQ</button></div></header>
  {active==="Tickets"?<section className="ticketsPage"><div className="ticketIntro"><div><span>SUPPORT WORKFLOW</span><h2>Customer tickets</h2><p>Create, track and resolve every support request from one workspace.</p></div><div><b>{liveTickets.filter(t=>t.status==="open").length}</b><small>Open tickets</small></div></div><div className="ticketGrid"><form className="ticketForm" onSubmit={createTicket}><h3>Create new ticket</h3><p>Describe the customer issue and choose its urgency.</p><label>Subject<input value={ticketForm.subject} onChange={e=>setTicketForm({...ticketForm,subject:e.target.value})} placeholder="e.g. Billing payment failed" required/></label><label>Description<textarea value={ticketForm.description} onChange={e=>setTicketForm({...ticketForm,description:e.target.value})} placeholder="Add useful details for the support agent..." required/></label><label>Priority<select value={ticketForm.priority} onChange={e=>setTicketForm({...ticketForm,priority:e.target.value})}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label>{ticketMessage&&<div className="ticketMessage">{ticketMessage}</div>}<button disabled={loading}>{loading?"Creating...":"Create ticket →"}</button></form><div className="ticketList"><div className="ticketListHead"><div><h3>Your tickets</h3><p>Live records from the SupportIQ database</p></div><button onClick={loadTickets}>↻ Refresh</button></div>{liveTickets.length===0?<div className="emptyTickets"><b>No tickets yet</b><span>Create your first support request using the form.</span></div>:liveTickets.map(t=><article key={t.id}><div className="ticketId">SQ-{String(t.id).padStart(4,"0")}</div><div><h4>{t.subject}</h4><p>{t.description}</p><small>{new Date(t.created_at).toLocaleString()}</small></div><div className="ticketTags"><em className={t.priority}>{t.priority}</em><em className={t.status}>● {t.status}</em></div></article>)}</div></div></section>:active==="AI Assistant"?<section className="chat"><div className="chatHead"><i>✦</i><div><h2>SupportIQ Assistant</h2><p>● Connected to 128 knowledge articles</p></div></div><div className="messages">{chat.map((x,i)=><div key={i} className={x.bot?"bubble bot":"bubble user"}>{x.text}</div>)}</div><div className="chips"><button onClick={()=>setMessage("How do I update billing?")}>Update billing</button><button onClick={()=>setMessage("Create a support ticket")}>Create ticket</button><button onClick={()=>setMessage("How do integrations work?")}>Integrations</button></div><div className="composer"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Ask SupportIQ anything..."/><button onClick={send}>Send ↑</button></div></section>:<>
   <section className="hero"><div><span>AI OPERATIONS CENTER</span><h2>Good morning, Usaid.</h2><p>Your support team is performing strongly. AI resolved <b>82% of conversations</b> this week.</p></div><div className="pulse"><b>82%</b><small>AI resolution</small></div></section>
   <section className="stats">{[["Open tickets","24","↓ 12%"],["Avg. response","1m 42s","↓ 18%"],["Customer satisfaction","94.8%","↑ 3.2%"],["AI conversations","1,284","+216"]].map(x=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><em>{x[2]}</em><small>vs last week</small></article>)}</section>
   <section className="grid"><article className="panel"><div className="panelHead"><div><h3>Conversation volume</h3><p>AI and human-assisted conversations</p></div><select><option>Last 7 days</option></select></div><div className="chart">{[42,58,48,75,63,86,70].map((h,i)=><div className="barWrap" key={i}><div className="bar" style={{height:`${h}%`}}><i/></div><span>{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"][i]}</span></div>)}</div><div className="legend">● AI resolved　<span>● Agent assisted</span></div></article><article className="panel performance"><div className="panelHead"><div><h3>AI performance</h3><p>Quality across all conversations</p></div><button>View report →</button></div><div className="score"><i><b>92</b><small>/100</small></i><div><b>Excellent</b><span>+4 points this month</span></div></div>{[["Answer accuracy",96],["Intent detection",93],["Helpful responses",91],["Safe handoffs",88]].map(x=><div className="progress" key={x[0] as string}><span>{x[0]}</span><b>{x[1]}%</b><i><u style={{width:`${x[1]}%`}}/></i></div>)}</article></section>
   <section className="panel ticketPanel"><div className="panelHead"><div><h3>{active==="Tickets"?"All support tickets":"Recent tickets"}</h3><p>Live queue from customers and AI handoffs</p></div><button onClick={()=>setActive("Tickets")}>View all tickets →</button></div><div className="table"><div className="row head">{["Ticket","Customer","Subject","Priority","Status","Updated"].map(x=><span key={x}>{x}</span>)}</div>{tickets.map(t=><div className="row" key={t[0]}><b>{t[0]}</b><span>{t[1]}</span><span>{t[2]}</span><span><em className={t[3].toLowerCase()}>{t[3]}</em></span><span><em className={t[4].toLowerCase()}>● {t[4]}</em></span><span>{t[5]}</span></div>)}</div></section>
  </>}</section>
 </main>
}
